import math

import torch
import torch.nn as nn
import torch.nn.functional as F


class TaskEdgeScorerMask(nn.Module):
    """Task-specific edge mask generated by a shared edge scorer."""

    def __init__(
        self,
        adjacency: torch.Tensor,
        embedding_dim: int,
        scorer_dim: int = 16,
        keep_ratio: float = 0.8,
        temperature: float = 1.0,
    ):
        super().__init__()

        if not 0.0 < keep_ratio <= 1.0:
            raise ValueError(
                "keep_ratio must be in (0, 1]."
            )

        adjacency = adjacency.coalesce()

        self.num_nodes = adjacency.size(0)
        self.keep_ratio = keep_ratio
        self.temperature = temperature

        indices = adjacency.indices()
        values = adjacency.values()

        row = indices[0]
        col = indices[1]

        # --------------------------------------------------
        # Fixed self-loops
        # --------------------------------------------------
        self_loop = row == col

        self.register_buffer(
            "self_indices",
            indices[:, self_loop],
        )

        self.register_buffer(
            "self_values",
            values[self_loop],
        )

        # --------------------------------------------------
        # Non-self sparse entries
        # --------------------------------------------------
        non_self = ~self_loop

        row = row[non_self]
        col = col[non_self]
        values = values[non_self]

        # Canonical undirected pairs.
        pair_src = torch.minimum(
            row,
            col,
        )
        pair_dst = torch.maximum(
            row,
            col,
        )

        pair_ids = (
            pair_src * self.num_nodes
            + pair_dst
        )

        (
            unique_pair_ids,
            edge_to_pair,
        ) = torch.unique(
            pair_ids,
            sorted=True,
            return_inverse=True,
        )

        unique_src = (
            unique_pair_ids
            // self.num_nodes
        )

        unique_dst = (
            unique_pair_ids
            % self.num_nodes
        )

        self.register_buffer(
            "pair_src",
            unique_src,
        )

        self.register_buffer(
            "pair_dst",
            unique_dst,
        )

        self.register_buffer(
            "edge_indices",
            torch.stack(
                [row, col],
                dim=0,
            ),
        )

        self.register_buffer(
            "edge_values",
            values,
        )

        self.register_buffer(
            "edge_to_pair",
            edge_to_pair,
        )

        self.num_edge_pairs = (
            unique_pair_ids.numel()
        )

        # --------------------------------------------------
        # Shared low-rank task-specific edge scorer
        # --------------------------------------------------
        self.projection = nn.Linear(
            embedding_dim,
            scorer_dim,
            bias=False,
        )

    def compute_logits(
        self,
        embeddings: torch.Tensor,
    ) -> torch.Tensor:
        """Score every existing undirected edge."""

        src = embeddings[
            self.pair_src
        ]

        dst = embeddings[
            self.pair_dst
        ]

        src = self.projection(src)
        dst = self.projection(dst)

        # Normalize to avoid pretrained embedding norm
        # dominating edge selection.
        src = F.normalize(
            src,
            p=2,
            dim=-1,
        )

        dst = F.normalize(
            dst,
            p=2,
            dim=-1,
        )

        # Symmetric relation:
        # score(i, j) == score(j, i)
        logits = (
            src * dst
        ).sum(dim=-1)

        return logits

    def _topk_mask(
        self,
        logits: torch.Tensor,
    ) -> torch.Tensor:
        if self.keep_ratio >= 1.0:
            return torch.ones_like(
                logits
            )

        num_keep = max(
            1,
            math.ceil(
                self.keep_ratio
                * logits.numel()
            ),
        )

        _, indices = torch.topk(
            logits,
            k=num_keep,
            dim=0,
        )

        hard_mask = torch.zeros_like(
            logits
        )

        hard_mask = hard_mask.scatter(
            dim=0,
            index=indices,
            value=1.0,
        )

        return hard_mask

    def forward(
        self,
        embeddings: torch.Tensor,
    ):
        # --------------------------------------------------
        # Edge preference generated from pretrained features
        # --------------------------------------------------
        logits = self.compute_logits(
            embeddings
        )

        # Surrogate used only for backward.
        soft_mask = torch.sigmoid(
            logits / self.temperature
        )

        # Actual forward graph.
        hard_mask = self._topk_mask(
            logits
        )

        if self.training:
            pair_mask = (
                hard_mask.detach()
                - soft_mask.detach()
                + soft_mask
            )
        else:
            pair_mask = hard_mask

        # Same canonical mask controls (i,j) and (j,i).
        edge_mask = pair_mask[
            self.edge_to_pair
        ].to(
            self.edge_values.dtype
        )

        masked_values = (
            self.edge_values
            * edge_mask
        )

        # Fixed self-loops.
        if self.self_values.numel() > 0:
            output_indices = torch.cat(
                [
                    self.edge_indices,
                    self.self_indices,
                ],
                dim=1,
            )

            output_values = torch.cat(
                [
                    masked_values,
                    self.self_values,
                ],
                dim=0,
            )
        else:
            output_indices = (
                self.edge_indices
            )

            output_values = (
                masked_values
            )

        masked_adj = torch.sparse_coo_tensor(
            output_indices,
            output_values,
            (
                self.num_nodes,
                self.num_nodes,
            ),
            dtype=output_values.dtype,
            device=output_values.device,
        ).coalesce()

        return (
            masked_adj,
            hard_mask,
            soft_mask,
            logits,
        )